version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9077 start_with_request=yes"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    links:
      - 'php'
    volumes:
      - .:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8077:80"

networks:
  default:
    driver: bridge
